### PR TITLE
add support for manipulating Vuex state

### PR DESCRIPTION
**Pull request by jblotus**
implements #7

### CODE REVIEW

**Comment by nelsonpecora** [comment]
Hey, do you know what happened with this? It would be super useful, but doesn't look like it was merged in (or even discussed).

**Comment by jblotus** [comment]
I didn't get any response so I closed it. I decided against using vue-unit at this time. I'm sticking to testing vuex stuff directly and avoiding ui testing for now.

**Comment by nelsonpecora** [comment]
Ah, no worries

**Comment by ghost** [comment]
@wrseward If you have time, could we reopen this PR? I would love to implement vue-unit into my project, but without this feature I'm unable to. I'm guessing some others would feel the same as well

**Pull request closed without merging**
